all:
	g++ -o Ejercicio3Cliente Ejercicio3Cliente.cpp -lrt -lpthread
	g++ -o Ejercicio3Servidor Ejercicio3Servidor.cpp -lrt -lpthread
Cliente: 
	g++ -o Ejercicio3Cliente Ejercicio3Cliente.cpp -lrt
Servidor:
	g++ -o Ejercicio3Servidor Ejercicio3Servidor.cpp -lrt -lpthread