all:
	g++ -o Ejercicio3Cliente Ejercicio3Cliente.cpp
	g++ -o Ejercicio3Servidor Ejercicio3Servidor.cpp
Cliente: 
	g++ -o Ejercicio3Cliente Ejercicio3Cliente.cpp
Servidor:
	g++ -o Ejercicio3Servidor Ejercicio3Servidor.cpp