all:
	g++ -o Ejercicio3Cliente Ejercicio3Cliente.cpp -lrt
	g++ -o Ejercicio3Servidor Ejercicio3Servidor.cpp -lrt
Cliente: 
	g++ -o Ejercicio3Cliente Ejercicio3Cliente.cpp -lrt
Servidor:
	g++ -o Ejercicio3Servidor Ejercicio3Servidor.cpp -lrt